baseURL = 'https://arkhamcookie.github.io/moonwalk/'
languageCode = 'en-US'
title = 'A demo site for the moonwalk theme.'

[params]
  [params.author]
    name = 'ArkhamCookie'
	[params.social]
		github = 'https://github.com/ArkhamCookie'
		mastadon = 'https://tilde.zone/@ArkhamCookie'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
