baseURL = 'https://arkhamcookie.github.io/moonwalk/'
languageCode = 'en-US'
title = 'Moonwalk'

[menus]
  [[menus.main]]
    name = 'about'
    pageRef = '/about'

  [[menus.main]]
    name = 'blog'
    pageRef = '/blog'

	[[menus.main]]
		name = 'website'
		url = 'https://arkhamcookie.com'

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
