baseURL = 'https://arkhamcookie.github.io/moonwalk/'
languageCode = 'en-US'
title = 'Moonwalk'

[menus]
  [[menus.main]]
    name = 'about'
    pageRef = '/about'

  [[menus.main]]
    name = 'blog'
    pageRef = '/blog'

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'

[params]
  [params.author]
    name = 'ArkhamCookie'
	[params.social]
		github = 'https://github.com/ArkhamCookie'
		mastadon = 'https://tilde.zone/@ArkhamCookie'
		website = 'https://arkhamcookie.com'
