name = "moonwalk"
license = "MIT"
licenseLink = "https://github.com/ArkhamCookie/moonwalk-hugo/blob/main/LICENSE"
description = "A port of moonwalk to Hugo."

homepage = "https://github.com/ArkhamCookie/moonwalk-hugo"

demosite = "https://arkhamcookie.github.io/moonwalk-hugo"

[author]
	name = "ArkhamCookie"
	homepage = "https://arkhamcookie.com"

[original]
	author = "abhinavs"
	homepage = "https://github.com/abhinavs"
	repo = "https://github.com/abhinavs/moonwalk"
