baseURL = 'https://arkhamcookie.github.io/moonwalk-hugo/'
languageCode = 'en-US'
title = 'Moonwalk'

theme = "moonwalk-hugo"

[menus]
  [[menus.main]]
    name = 'about'
    pageRef = '/about'

  [[menus.main]]
    name = 'blog'
    pageRef = '/blog'

	[[menus.main]]
		name = 'website'
		url = 'https://arkhamcookie.com'

[params]
	[params.author]
		email = 'example@example.com'
